# Week 4 Assignment 
Use this notebook to complete week 4 assignment of the Python Bootcamp for Data course. Each question is described with a Markdown cell explaining the requirements and expectations. Update the corresponding cells and as always, wait until the autograding completes on your GitHub repository 

The variables in the question cells are pre-assigned to `None` so that you can reuse them. The autograding tests uses those variables names to ensure the expected values are present. Do not change the variable names, otherwise a `NameError` will show in the autograding test logs.

In [1]:
import pandas as pd
import numpy as np

## Question 1
Load the `city_census.csv` dataset in this repo, assign the dataframe to `df1` and manipulate the dataframe so that:
- Only 15 items are present
- Exports to a Python dictionary

Assign the Python dictionary with the 15 items from the dataframe to `df1_dict`

In [2]:
df1 = pd.read_csv("city_census.csv")
df1_dict = df1.head(15).to_dict()
df1_dict

{'first': {0: 'Earl',
  1: 'Vikki',
  2: 'Elizabeth',
  3: 'Edwina',
  4: 'Thomas',
  5: 'Martha',
  6: 'Danny',
  7: 'Beverly',
  8: 'Martha',
  9: 'Ofelia',
  10: 'Christina',
  11: 'Barbara',
  12: 'Anita',
  13: 'Clinton',
  14: 'Judy'},
 'last': {0: 'Myrick',
  1: 'Gallegos',
  2: 'Binegar',
  3: 'Garcia',
  4: 'Hinkle',
  5: 'Hudgins',
  6: 'Wilson',
  7: 'Skinner',
  8: 'Brown',
  9: 'Williams',
  10: 'Jiggetts',
  11: 'Sale',
  12: 'Everhardt',
  13: 'Turner',
  14: 'Gramm'},
 'age': {0: 36,
  1: 31,
  2: 15,
  3: 53,
  4: 2,
  5: 31,
  6: 55,
  7: 67,
  8: 2,
  9: 82,
  10: 15,
  11: 35,
  12: 46,
  13: 66,
  14: 51},
 'state': {0: 'Iowa',
  1: 'Iowa',
  2: 'Nebraska',
  3: 'Arizona',
  4: 'Georgia',
  5: 'Utah',
  6: 'Iowa',
  7: 'Missouri',
  8: 'Illinois',
  9: 'New Mexico',
  10: 'New Jersey',
  11: 'Virginia',
  12: 'Oregon',
  13: 'Georgia',
  14: 'West Virginia'},
 'weight': {0: 208.0,
  1: 187.0,
  2: nan,
  3: 170.0,
  4: nan,
  5: 227.0,
  6: 205.0,
  7: 233.0,
  8: nan,
  9: 192.0,
  10: nan,
  11: 170.0,
  12: 157.0,
  13: 208.0,
  14: 217.0}}

## Question 2

Load the `city_census.csv` dataset again. There are some rows where the `weight` value is `NaN`. Drop those rows from the `dataframe` and assign the resulting value to the `df2` variable. 
Hint: Make sure that the dropped rows are reflected in the dataframe, otherwise the test will fail.

In [3]:
df2 = pd.read_csv("city_census.csv")
df2.dropna(inplace=True)
df2

      first      last  age       state  weight
0      Earl    Myrick   36        Iowa   208.0
1     Vikki  Gallegos   31        Iowa   187.0
3    Edwina    Garcia   53     Arizona   170.0
5    Martha   Hudgins   31        Utah   227.0
6     Danny    Wilson   55        Iowa   205.0
..      ...       ...  ...         ...     ...
395     Amy    Spears   54      Nevada   231.0
396  Deanna   Custard   28  Washington   154.0
397     Amy     Hicks   86    Kentucky   241.0
398     Tom    London   44     Vermont   146.0
399    Alex      Hull   81      Nevada   243.0

[319 rows x 5 columns]

## Question 3

Load the `city_census.csv` dataset again. Manipulate the `dataframe` so that only entries from North Carolina are present. Assign the resulting dataframe to the `df3` variable.

In [4]:
df3 = pd.read_csv("city_census.csv")
df3.query("state == 'North Carolina'", inplace=True)
df3

       first       last  age           state  weight
213   Robert      Smith   21  North Carolina   241.0
244  Richard       Winn   77  North Carolina   146.0
311   Walter  Ballinger   56  North Carolina   146.0
312     Ryan     Phelps   67  North Carolina   214.0
392   Rodney   Sullivan   67  North Carolina   173.0

## Question 4

Load the `city_census.csv` dataset again. Manipulate the `dataframe` so that only 20 entries with persons that are over 150 in weight are used. Assign the resulting `dataframe` to the `df4` variable.

In [5]:
df4 = pd.read_csv("city_census.csv")
df4 = df4.query("weight > 150").head(20)
df4

        first       last  age          state  weight
0        Earl     Myrick   36           Iowa   208.0
1       Vikki   Gallegos   31           Iowa   187.0
3      Edwina     Garcia   53        Arizona   170.0
5      Martha    Hudgins   31           Utah   227.0
6       Danny     Wilson   55           Iowa   205.0
7     Beverly    Skinner   67       Missouri   233.0
9      Ofelia   Williams   82     New Mexico   192.0
11    Barbara       Sale   35       Virginia   170.0
12      Anita  Everhardt   46         Oregon   157.0
13    Clinton     Turner   66        Georgia   208.0
14       Judy      Gramm   51  West Virginia   217.0
16     Louise     Magana   19       Virginia   174.0
17       John    Rosales   55      Minnesota   165.0
18  Christine       Ware   32     Washington   191.0
20       Lois       Ford   29        Vermont   189.0
21      Joyce      Sites   64          Texas   211.0
22        Dan      Stone   40        Arizona   193.0
23      Rosie        Doe   52       New York   222.0
26      James   Williams   55       Virginia   208.0
28      Henry     Silmon   77         Oregon   227.0

## Question 5

Load the `city_census.csv` dataset again. Manipulate the `dataframe` so that it holds anyone that is over 200 in weight from the state of California. Assign the resulting `dataframe` to the `df5` variable.

In [6]:
df5 = pd.read_csv("city_census.csv")
df5.query("weight > 200 & state == 'California'", inplace=True)
df5

        first     last  age       state  weight
66   Rosemary      Cox   44  California   231.0
196     David  Shannon   57  California   242.0

## Question 6

Manipulate the `dataframe` so that it holds anyone that has a first name that includes the (exact) `"al"` letters. Assign the resulting operation to the `df6` variable.

In [7]:
df6 = pd.read_csv("city_census.csv")
df6.query("first.str.contains('al', na=False)", engine="python", inplace=True)
df6

       first       last  age           state  weight
91    Dallas     Conrad   22         Arizona   164.0
116     Kala    Boynton   52        Kentucky   206.0
304   Gerald   Williams   83      New Jersey   200.0
311   Walter  Ballinger   56  North Carolina   146.0
351   Tamala     Duncan   20       Wisconsin   139.0
357    Ralph   Sherrill   12          Alaska     NaN
394  Randall      Brown   39        Arkansas   148.0

## Question 7

Create a function to manipulate the `dataframe` so that it updates any `NaN` value from the `weight` columnn to 0. Assign the resulting operation on the `dataframe` to the `df7` variable.

Hint: Use `math.isnan()` to check if a value is `NaN`

In [8]:
import math

# Hint: use math.isnan function to check if a value is NaN when you create your
# helper function
def nan_to_zero(weight):
    if math.isnan(weight):
        return 0
    return weight

df7 = pd.read_csv("city_census.csv")
df7["weight"] = df7["weight"].apply(nan_to_zero)
df7

         first      last  age       state  weight
0         Earl    Myrick   36        Iowa   208.0
1        Vikki  Gallegos   31        Iowa   187.0
2    Elizabeth   Binegar   15    Nebraska     0.0
3       Edwina    Garcia   53     Arizona   170.0
4       Thomas    Hinkle    2     Georgia     0.0
..         ...       ...  ...         ...     ...
395        Amy    Spears   54      Nevada   231.0
396     Deanna   Custard   28  Washington   154.0
397        Amy     Hicks   86    Kentucky   241.0
398        Tom    London   44     Vermont   146.0
399       Alex      Hull   81      Nevada   243.0

[400 rows x 5 columns]

## Question 8

Manipulate the `dataframe` so that it has a new column called `"health_issue"`. This column should have only `1` or `0`. If the person is above `240` in weight, this column should have a `1`. Otherwise a `0`. Assign the resulting operation on the `dataframe` to the `df8` variable.

Hint: first create the `health_issue` column with the matching weight and then use a function to transform the boolean into a 1 or a 0. Don't forget to assign values to new columns!

In [9]:
def check_above_240(weight):
    if weight > 240:
        return 1
    return 0

df8 = pd.read_csv("city_census.csv")
df8["health_issue"] = df8["weight"].apply(check_above_240)
df8

         first      last  age       state  weight  health_issue
0         Earl    Myrick   36        Iowa   208.0             0
1        Vikki  Gallegos   31        Iowa   187.0             0
2    Elizabeth   Binegar   15    Nebraska     NaN             0
3       Edwina    Garcia   53     Arizona   170.0             0
4       Thomas    Hinkle    2     Georgia     NaN             0
..         ...       ...  ...         ...     ...           ...
395        Amy    Spears   54      Nevada   231.0             0
396     Deanna   Custard   28  Washington   154.0             0
397        Amy     Hicks   86    Kentucky   241.0             1
398        Tom    London   44     Vermont   146.0             0
399       Alex      Hull   81      Nevada   243.0             1

[400 rows x 6 columns]

## Question 9

Load the `city_census.csv` dataset again. Manipulate the `dataframe` so that all rows having `"North Carolina"`for state, have `N. Carolina` instead. Assign the resulting operation on the `dataframe` to the `df9` variable.

In [10]:
df9 = pd.read_csv("city_census.csv")
df9["state"] = df9["state"].str.replace("North Carolina", "N. Carolina")
df9

         first      last  age       state  weight
0         Earl    Myrick   36        Iowa   208.0
1        Vikki  Gallegos   31        Iowa   187.0
2    Elizabeth   Binegar   15    Nebraska     NaN
3       Edwina    Garcia   53     Arizona   170.0
4       Thomas    Hinkle    2     Georgia     NaN
..         ...       ...  ...         ...     ...
395        Amy    Spears   54      Nevada   231.0
396     Deanna   Custard   28  Washington   154.0
397        Amy     Hicks   86    Kentucky   241.0
398        Tom    London   44     Vermont   146.0
399       Alex      Hull   81      Nevada   243.0

[400 rows x 5 columns]

## Question 10

From the NumPy array below, split in two equal parts and then reduce the resulting arrays by having only values higher than 15.

In [11]:
array = np.array([18, 11, 8, 33, 23, 42, 82, 11, 8, 7, 1, 23])
# Assign your splits to these variables, remember to reduce them with values only higher than 15
array_split_1, array_split_2 = np.hsplit(array, 2)

array_split_1 = array_split_1[array_split_1 > 15]
array_split_2 = array_split_2[array_split_2 > 15]

array_split_1, array_split_2

(array([18, 33, 23, 42]), array([82, 23]))